[package]
name = "ssh-config-add"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.40", features = ["derive"] }
handlebars = "6.3.2"
serde = "1.0.219"
serde_json = "1.0.140"
